### ISSUE TITLE
policy-reporter Unable to Locate policyreport and clusterpolicyreport CRDs

### ISSUE THREAD

**Issue by shin-go** [kyverno/policy-reporter#39]
Inspecting logs for the `policy-reporter` pod, I'm seeing log entries like so:
```
2021/05/24 20:54:14 [INFO] Resource not Found: wgpolicyk8s.io/v1alpha2, Resource=clusterpolicyreports                                                               
2021/05/24 20:54:14 [INFO] Resource not Found: wgpolicyk8s.io/v1alpha2, Resource=policyreports
2021/05/24 21:50:29 [INFO] Resource not Found: wgpolicyk8s.io/v1alpha1, Resource=policyreports
2021/05/24 21:52:36 [INFO] Resource not Found: wgpolicyk8s.io/v1alpha1, Resource=clusterpolicyreports 
```
Comparing to the CRDs in my k8s cluster, the `policyreports` and `clusterpolicyreports` CRDs are defined like so (truncated for brevity - these are Kyverno's CRDs and very lengthy):
```
### policyreports CRD ###
Name:         policyreports.wgpolicyk8s.io 
Namespace:
Labels: <none>
Annotations:  controller-gen.kubebuilder.io/version: v0.4.0 
API Version:  apiextensions.k8s.io/v1
Kind:         CustomResourceDefinition
# ...and so on
```
```
### clusterpolicyreports CRD ###
Name:         clusterpolicyreports.wgpolicyk8s.io
Namespace:
Labels: <none>
Annotations:  controller-gen.kubebuilder.io/version: v0.4.0 
API Version:  apiextensions.k8s.io/v1
Kind:         CustomResourceDefinition
# ...and so on
```

I'm running Kyverno `v1.3.6` for reference, which I installed from their [globbed manifest](https://raw.githubusercontent.com/kyverno/kyverno/main/definitions/release/install.yaml) with minimal changes - I only modified the namespace label in each resource. The only reference to `wgpolicyk8s.io/v1alpha*` in their manifest is for the ClusterRole. So the CRDs exist, but aren't under the API policy-reporter seems to expect as defined in `pkg/kubernetes/report_adapter.go`.

Please let me know if there's any additional info I can provide!

**Comment by fjogeleit** [comment]
Hey, in my test installation on a fresh cluster it also worked with the globbed manifests for me.

Can you please check if you have a ServiceAccount, ClusterRole and ClusterRoleBinding with the name "policy-reporter" in the `policy-reporter` namespace and if your Deployment of Policy Reporter use this ServiceAccount?

**Comment by shin-go** [comment]
Ah that was it. I was missing the `policy-reporter` ServiceAccount, and verified getting messages into Slack.

**Comment by fjogeleit** [comment]
Great! Thanks for your feedback
