### ISSUE TITLE
Yandex Object Storage Target

### ISSUE THREAD

**Issue by nar3k** [kyverno/policy-reporter#55]
**Motivation**

Hi - Im from Yandex.Cloud solution architect team. I believe that kyverno is the best way to manage kubernetes policies. But Yandex.Cloud users demand export to Yandex.Cloud storages

**Feature**

Yandex Cloud has multiple services that can be targets,but most demanded output right now is [Yandex.Storage](https://cloud.yandex.com/en-ru/services/storage) which has [S3 API](https://cloud.yandex.com/en-ru/docs/storage/s3/api-ref/)

**Additional context**

I could implement this feature by my own - Recently I added Yandex.Storage  as part of falcosidekick  https://github.com/falcosecurity/falcosidekick/pull/261

**Comment by fjogeleit** [comment]
hey, thank you for this suggestion. You are welcome to implement it on your own. Let me know if you need any help.

**Comment by fjogeleit** [comment]
Thank you for your contribution. Yandex is available with Helm Version v1.11.0. Would be great if you can test it,
