### ISSUE TITLE
Update UI Ingress to use networking.k8s.io/v1 api version

### ISSUE THREAD

**Issue by z0rc** [kyverno/policy-reporter#56]
```
networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```
https://github.com/kyverno/policy-reporter/blob/policy-reporter-1.8.6/charts/policy-reporter/charts/ui/templates/ingress.yaml#L4-L8 Uses outdated logic for Ingress apiVersion.

Helm recently updated default ingress template to support new apiVersion and new spec fields. You can use as reference.

**Comment by fjogeleit** [comment]
Thanks for your request.

The Helm Chart was updated and the new Ingress Configuration is released with 1.8.7
