### ISSUE TITLE
policy-reporter 1.8.5 missing from Docker hub

### ISSUE THREAD

**Issue by z0rc** [kyverno/policy-reporter#60]
https://github.com/kyverno/policy-reporter/pull/58/files#diff-892d0c98e0e009d28a0ff1ea944c97db2fbbb4d71b53f92b3736c8780e824f25R9 updated policy-reporter container version to 1.8.5, but it isn't available in docker hub https://hub.docker.com/r/fjogeleit/policy-reporter/tags

**Comment by fjogeleit** [comment]
Sorry, my fail. It is added now.

https://hub.docker.com/layers/fjogeleit/policy-reporter/1.8.5/images/sha256-bade8f4dfcc329df3e44c7ebc1771c8ded515bdce4f84289cdae44e3ebb97ec5?context=repo
