### ISSUE TITLE
namespace for monitoring resources doesnt work correctly anymore

### ISSUE THREAD

**Issue by MaxRink** [kyverno/policy-reporter#61]
https://github.com/kyverno/policy-reporter/commit/faeac457243283e1643e003bae79fe4570357e93 broke https://github.com/kyverno/policy-reporter/blob/2107907a3a5ffdef10183db4d6c718444e660a77/charts/policy-reporter/values.yaml#L81
So now not every resource inherits the namespace set there and the default  `cattle-dashboards' gets used.

**Comment by fjogeleit** [comment]
Thanks for reporting. I will check this.

**Comment by fjogeleit** [comment]
This issue is fixed with version 1.8.9
